name: Go
on: [push]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v3

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Test
        run: go test -v ./...

      - name: Vet
        run: go vet ./...
