name: Go
on: [push]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: cat
        # run: sudo apt update -yqq && sudo apt install grep coreutils -yqq
        run: cat go.mod

      - name: which
        run: which grep

      - name: version
        run: grep --version

      - name: grep 
        run: grep '^go ' go.mod

      - name: Get Go version
        run: echo "GO_VERSION=$(grep 'go \d\.' go.mod | cut -d ' ' -f 2)" >> $GITHUB_ENV && cat $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Test
        run: go test -v ./...

      - name: Vet
        run: go vet ./...
