name: Shell
on: [push]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up
        run: sudo apt-get install -y shellcheck zsh

      - name: Test
        run: scripts/test.sh
