name: Shell
on: [push]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Set up
        run: sudo apt-get install -y shellcheck zsh

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: scripts/test.sh
